Main mobile
hydaline-code/Portfolio_mobilefirst pull request #1
Opened 2023-05-31 21:25 UTC by hydaline-code

Hello hope this meets you fine.This is the beginning of how to showcase ourself in the world of tech. Please kindly give feedbacks ♻ to my portfolio setup project so I can improve my work.

2023-05-31 22:02 UTC, Ofarouq310 reviewed
Hi @hydaline-code , ✋  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code. 🥈 

![giphy](https://github.com/Fentahunn/portfolio_one/assets/102612396/aa365bb5-fddd-49e3-a285-ea548ce42cba)

## 🔴 Invalid Code Review Request  

- Your Pull request title should be short, and concise, and addresses what you are implementing, in your case, it could be, `Add header and headline sections` or something similar, simpler. Please refer to the next picture to help you how to edit the title.
![image](https://github.com/Fentahunn/portfolio_one/assets/102612396/acfbea30-fa50-4379-91f9-0bb9d45bd16d)

-  As for the PR description, you should simplify it even more, just summarizing what you added in a bullet list or number list, take a look at this example, to edit the description, just click on three dots on the right side, then click on edit.
![image](https://github.com/Fentahunn/portfolio_one/assets/102612396/f16c077a-f8e1-4035-9cf4-cfe78dac955b)



- Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-01 09:05 UTC, bobb-Rob requested changes
## STATUS: CHANGES REQUIRED ♻️
Hi @hydaline-code, 

Good job so far! 👏👏👏 
There are some issues that you still need to work on to go to the next project but you are almost there!  😃 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>
![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-01 09:05 UTC, bobb-Rob commented on index.html
> +      </button>
You have done very well implementing this project without any serious issues with your code. Well done. 

- [ ] I noticed a little issue with the `Start Collaboration`, it has a gray color border that should be removed. This border is a default style of buttons. Kindly add `border: none;` to the `.headline-btn` class. 

Your button | Figma Button
---- | ----
![image](https://github.com/hydaline-code/Portfolio_mobilefirst/assets/84156714/5ad4d128-4608-40d7-94c9-3a3bc1747238) | ![image](https://github.com/hydaline-code/Portfolio_mobilefirst/assets/84156714/811bf47d-80e2-461e-89bf-fd9b7a9c004c)

2023-06-01 09:05 UTC, bobb-Rob commented on index.html
> +      </div>
- [ ] This section's background image should be applied to the page using the CSS `background-image` property. Usually, if an image is not part of the content (aesthetic reasons) use CSS background-image. [Check this link](https://stackoverflow.com/questions/492809/when-to-use-img-vs-css-background-image) for more info.


```html
<div class="headline-img">
        <img src="./images/image_geometry_2.png" alt="intro image">
      </div>
```

2023-06-01 16:19 UTC, frank1738 approved these changes
Hi @hydaline-code , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/tIeCLkB8geYtW/giphy.gif"/>

## Highlights

✅ Correct use of Github workflow
✅ No linter error
✅ Good Design 👍 

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-02 11:24 UTC, merged